name: Build and Deploy

on:
  push:
    branches:
      - main  # Cambia esto al nombre de la rama que usas para desplegar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Build Docker image
      run: |
        docker build -t alvarocamposdev/pokedex:latest .

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image to Docker Hub
      run: |
        docker push alvarocamposdev/pokedex:latest

    - name: Deploy application
      run: |
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} root@vmi2024848 << 'EOF'
          docker pull alvarocamposdev/pokedex:latest
          docker stop pokedex || true
          docker rm pokedex || true
          docker run -d --name pokedex -p 80:80 alvarocamposdev/pokedex:latest
        EOF
