name: Build and Deploy

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Build Docker image
      run: |
        docker build -t alvarocamposdev/pokedex:latest .

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image to Docker Hub
      run: |
        docker push alvarocamposdev/pokedex:latest

    - name: Create private key file
      run: |
        echo "${{ secrets.SSH_USER }}" > private_key
        chmod 600 private_key

    - name: Deploy application
      run: |
        ssh -o StrictHostKeyChecking=no -i private_key root@185.245.183.183 << 'EOF'
          docker pull alvarocamposdev/pokedex:latest
          docker stop pokedex || true
          docker rm pokedex || true
          docker run -d --name pokedex -p 8080:80 alvarocamposdev/pokedex:latest
        EOF
